var objeto_material_conjunto_a=document.getElementById("objeto_material_conjunto_a")
var objeto_material_conjunto_b=document.getElementById("objeto_material_conjunto_b")
var objeto_material_conjunto_c=document.getElementById("objeto_material_conjunto_c")
var objeto_material_conjunto_d=document.getElementById("objeto_material_conjunto_d")
var objeto_material_conjunto_e=document.getElementById("objeto_material_conjunto_e")
var objeto_material_conjunto_f=document.getElementById("objeto_material_conjunto_f")
var objeto_material_conjunto_g=document.getElementById("objeto_material_conjunto_g")
var objeto_material_conjunto_h=document.getElementById("objeto_material_conjunto_h")
var objeto_material_conjunto_i=document.getElementById("objeto_material_conjunto_i")
var objeto_material_conjunto_j=document.getElementById("objeto_material_conjunto_j")
var objeto_material_conjunto_k=document.getElementById("objeto_material_conjunto_k")
var objeto_material_conjunto_l=document.getElementById("objeto_material_conjunto_l")
var objeto_material_conjunto_m=document.getElementById("objeto_material_conjunto_m")
var objeto_material_conjunto_n=document.getElementById("objeto_material_conjunto_n")
var objeto_material_conjunto_o=document.getElementById("objeto_material_conjunto_o")
var objeto_material_conjunto_p=document.getElementById("objeto_material_conjunto_p")
var objeto_material_conjunto_q=document.getElementById("objeto_material_conjunto_q")
var objeto_material_conjunto_r=document.getElementById("objeto_material_conjunto_r")
var objeto_material_conjunto_s=document.getElementById("objeto_material_conjunto_s")
var objeto_material_conjunto_t=document.getElementById("objeto_material_conjunto_t")
var objeto_material_conjunto_u=document.getElementById("objeto_material_conjunto_u")
var objeto_material_conjunto_v=document.getElementById("objeto_material_conjunto_v")
var objeto_material_conjunto_w=document.getElementById("objeto_material_conjunto_w")
var objeto_material_conjunto_x=document.getElementById("objeto_material_conjunto_x")
var objeto_material_conjunto_y=document.getElementById("objeto_material_conjunto_y")
var objeto_material_conjunto_z=document.getElementById("objeto_material_conjunto_z")
var objeto_material_conjunto_za=document.getElementById("objeto_material_conjunto_za")
var objeto_material_conjunto_zb=document.getElementById("objeto_material_conjunto_zb")
var objeto_material_conjunto_zc=document.getElementById("objeto_material_conjunto_zc")
var objeto_material_conjunto_zd=document.getElementById("objeto_material_conjunto_zd")
var objeto_material_conjunto_ze=document.getElementById("objeto_material_conjunto_ze")
var objeto_material_conjunto_zf=document.getElementById("objeto_material_conjunto_zf")
var objeto_material_conjunto_zg=document.getElementById("objeto_material_conjunto_zg")
var objeto_material_conjunto_zh=document.getElementById("objeto_material_conjunto_zh")
var objeto_material_conjunto_zi=document.getElementById("objeto_material_conjunto_zi")
var objeto_material_conjunto_zj=document.getElementById("objeto_material_conjunto_zj")
var objeto_material_conjunto_zk=document.getElementById("objeto_material_conjunto_zk")
var objeto_material_conjunto_zl=document.getElementById("objeto_material_conjunto_zl")
var objeto_material_conjunto_zm=document.getElementById("objeto_material_conjunto_zm")
var objeto_material_conjunto_zn=document.getElementById("objeto_material_conjunto_zn")
var objeto_material_conjunto_zo=document.getElementById("objeto_material_conjunto_zo")
var objeto_material_conjunto_zp=document.getElementById("objeto_material_conjunto_zp")
var objeto_material_conjunto_zq=document.getElementById("objeto_material_conjunto_zq")
var objeto_material_conjunto_zr=document.getElementById("objeto_material_conjunto_zr")
var objeto_material_conjunto_zs=document.getElementById("objeto_material_conjunto_zs")
var objeto_material_conjunto_zt=document.getElementById("objeto_material_conjunto_zt")
var objeto_material_conjunto_zu=document.getElementById("objeto_material_conjunto_zu")
var objeto_material_conjunto_zv=document.getElementById("objeto_material_conjunto_zv")

// console.log(objeto_material_conjunto_a)
// console.log(objeto_material_conjunto_b)
// console.log(objeto_material_conjunto_c)
// console.log(objeto_material_conjunto_d)
// console.log(objeto_material_conjunto_e)
// console.log(objeto_material_conjunto_f)
// console.log(objeto_material_conjunto_g)
// console.log(objeto_material_conjunto_h)
// console.log(objeto_material_conjunto_i)
// console.log(objeto_material_conjunto_j)
// console.log(objeto_material_conjunto_k)
// console.log(objeto_material_conjunto_l)
// console.log(objeto_material_conjunto_m)
// console.log(objeto_material_conjunto_n)
// console.log(objeto_material_conjunto_o)
// console.log(objeto_material_conjunto_p)
// console.log(objeto_material_conjunto_q)
// console.log(objeto_material_conjunto_r)
// console.log(objeto_material_conjunto_s)
// console.log(objeto_material_conjunto_t)
// console.log(objeto_material_conjunto_u)
// console.log(objeto_material_conjunto_v)
// console.log(objeto_material_conjunto_w)
// console.log(objeto_material_conjunto_x)
// console.log(objeto_material_conjunto_y)
// console.log(objeto_material_conjunto_z)
// console.log(objeto_material_conjunto_za)
// console.log(objeto_material_conjunto_zb)
// console.log(objeto_material_conjunto_zc)
// console.log(objeto_material_conjunto_zd)
// console.log(objeto_material_conjunto_ze)
// console.log(objeto_material_conjunto_zf)
// console.log(objeto_material_conjunto_zg)
// console.log(objeto_material_conjunto_zh)
// console.log(objeto_material_conjunto_zi)
// console.log(objeto_material_conjunto_zj)
// console.log(objeto_material_conjunto_zk)
// console.log(objeto_material_conjunto_zl)
// console.log(objeto_material_conjunto_zm)
// console.log(objeto_material_conjunto_zn)
// console.log(objeto_material_conjunto_zo)
// console.log(objeto_material_conjunto_zp)
// console.log(objeto_material_conjunto_zq)
// console.log(objeto_material_conjunto_zr)
// console.log(objeto_material_conjunto_zs)
// console.log(objeto_material_conjunto_zt)
// console.log(objeto_material_conjunto_zu)
// console.log(objeto_material_conjunto_zv)

function mostrarCatalogoTodo() {
    objeto_material_conjunto_a.style.display="flex"
    objeto_material_conjunto_b.style.display="flex"
    objeto_material_conjunto_c.style.display="flex"
    objeto_material_conjunto_d.style.display="flex"
    objeto_material_conjunto_e.style.display="flex"
    objeto_material_conjunto_f.style.display="flex"
    objeto_material_conjunto_g.style.display="flex"
    objeto_material_conjunto_h.style.display="flex"
    objeto_material_conjunto_i.style.display="flex"
    objeto_material_conjunto_j.style.display="flex"
    objeto_material_conjunto_k.style.display="flex"
    objeto_material_conjunto_l.style.display="flex"
    objeto_material_conjunto_m.style.display="flex"
    objeto_material_conjunto_n.style.display="flex"
    objeto_material_conjunto_o.style.display="flex"
    objeto_material_conjunto_p.style.display="flex"
    objeto_material_conjunto_q.style.display="flex"
    objeto_material_conjunto_r.style.display="flex"
    objeto_material_conjunto_s.style.display="flex"
    objeto_material_conjunto_t.style.display="flex"
    objeto_material_conjunto_u.style.display="flex"
    objeto_material_conjunto_v.style.display="flex"
    objeto_material_conjunto_w.style.display="flex"
    objeto_material_conjunto_x.style.display="flex"
    objeto_material_conjunto_y.style.display="flex"
    objeto_material_conjunto_z.style.display="flex"
    objeto_material_conjunto_za.style.display="flex"
    objeto_material_conjunto_zb.style.display="flex"
    objeto_material_conjunto_zc.style.display="flex"
    objeto_material_conjunto_zd.style.display="flex"
    objeto_material_conjunto_ze.style.display="flex"
    objeto_material_conjunto_zf.style.display="flex"
    objeto_material_conjunto_zg.style.display="flex"
    objeto_material_conjunto_zh.style.display="flex"
    objeto_material_conjunto_zi.style.display="flex"
    objeto_material_conjunto_zj.style.display="flex"
    objeto_material_conjunto_zk.style.display="flex"
    objeto_material_conjunto_zl.style.display="flex"
    objeto_material_conjunto_zm.style.display="flex"
    objeto_material_conjunto_zn.style.display="flex"
    objeto_material_conjunto_zo.style.display="flex"
    objeto_material_conjunto_zp.style.display="flex"
    objeto_material_conjunto_zq.style.display="flex"
    objeto_material_conjunto_zr.style.display="flex"
    objeto_material_conjunto_zs.style.display="flex"
    objeto_material_conjunto_zt.style.display="flex"
    objeto_material_conjunto_zu.style.display="flex"
    objeto_material_conjunto_zv.style.display="flex"
    }

function mostrarCatalogoTabiconSiete() {
    objeto_material_conjunto_a.style.display="flex"
    objeto_material_conjunto_b.style.display="flex"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoTabiconSieteCinco() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="flex"
    objeto_material_conjunto_d.style.display="flex"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoTabiconNueve() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="flex"
    objeto_material_conjunto_f.style.display="flex"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoBlockDiez() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="flex"
    objeto_material_conjunto_h.style.display="flex"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoBlockOnceCinco() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="flex"
    objeto_material_conjunto_j.style.display="flex"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoBlockDoce() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="flex"
    objeto_material_conjunto_l.style.display="flex"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoBlockHuecoDoce() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="flex"
    objeto_material_conjunto_n.style.display="flex"
    objeto_material_conjunto_o.style.display="flex"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoBlockHuecoQuince() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="flex"
    objeto_material_conjunto_q.style.display="flex"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoBlockQuince() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="flex"
    objeto_material_conjunto_s.style.display="flex"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoCuadro() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="flex"
    objeto_material_conjunto_u.style.display="flex"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoHexagono() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="flex"
    objeto_material_conjunto_w.style.display="flex"
    objeto_material_conjunto_x.style.display="flex"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoCruz() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="flex"
    objeto_material_conjunto_z.style.display="flex"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoPlaca() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="flex"
    objeto_material_conjunto_zb.style.display="flex"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoTabiqueRojo() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="flex"
    objeto_material_conjunto_zd.style.display="flex"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoAdopasto() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="flex"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoAceros() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="flex"
    objeto_material_conjunto_zg.style.display="flex"
    objeto_material_conjunto_zh.style.display="flex"
    objeto_material_conjunto_zi.style.display="flex"
    objeto_material_conjunto_zj.style.display="flex"
    objeto_material_conjunto_zk.style.display="flex"
    objeto_material_conjunto_zl.style.display="flex"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoEnvasados() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="flex"
    objeto_material_conjunto_zn.style.display="flex"
    objeto_material_conjunto_zo.style.display="flex"
    objeto_material_conjunto_zp.style.display="flex"
    objeto_material_conjunto_zq.style.display="flex"
    objeto_material_conjunto_zr.style.display="none"
    objeto_material_conjunto_zs.style.display="none"
    objeto_material_conjunto_zt.style.display="none"
    objeto_material_conjunto_zu.style.display="none"
    objeto_material_conjunto_zv.style.display="none"
}

function mostrarCatalogoAgregados() {
    objeto_material_conjunto_a.style.display="none"
    objeto_material_conjunto_b.style.display="none"
    objeto_material_conjunto_c.style.display="none"
    objeto_material_conjunto_d.style.display="none"
    objeto_material_conjunto_e.style.display="none"
    objeto_material_conjunto_f.style.display="none"
    objeto_material_conjunto_g.style.display="none"
    objeto_material_conjunto_h.style.display="none"
    objeto_material_conjunto_i.style.display="none"
    objeto_material_conjunto_j.style.display="none"
    objeto_material_conjunto_k.style.display="none"
    objeto_material_conjunto_l.style.display="none"
    objeto_material_conjunto_m.style.display="none"
    objeto_material_conjunto_n.style.display="none"
    objeto_material_conjunto_o.style.display="none"
    objeto_material_conjunto_p.style.display="none"
    objeto_material_conjunto_q.style.display="none"
    objeto_material_conjunto_r.style.display="none"
    objeto_material_conjunto_s.style.display="none"
    objeto_material_conjunto_t.style.display="none"
    objeto_material_conjunto_u.style.display="none"
    objeto_material_conjunto_v.style.display="none"
    objeto_material_conjunto_w.style.display="none"
    objeto_material_conjunto_x.style.display="none"
    objeto_material_conjunto_y.style.display="none"
    objeto_material_conjunto_z.style.display="none"
    objeto_material_conjunto_za.style.display="none"
    objeto_material_conjunto_zb.style.display="none"
    objeto_material_conjunto_zc.style.display="none"
    objeto_material_conjunto_zd.style.display="none"
    objeto_material_conjunto_ze.style.display="none"
    objeto_material_conjunto_zf.style.display="none"
    objeto_material_conjunto_zg.style.display="none"
    objeto_material_conjunto_zh.style.display="none"
    objeto_material_conjunto_zi.style.display="none"
    objeto_material_conjunto_zj.style.display="none"
    objeto_material_conjunto_zk.style.display="none"
    objeto_material_conjunto_zl.style.display="none"
    objeto_material_conjunto_zm.style.display="none"
    objeto_material_conjunto_zn.style.display="none"
    objeto_material_conjunto_zo.style.display="none"
    objeto_material_conjunto_zp.style.display="none"
    objeto_material_conjunto_zq.style.display="none"
    objeto_material_conjunto_zr.style.display="flex"
    objeto_material_conjunto_zs.style.display="flex"
    objeto_material_conjunto_zt.style.display="flex"
    objeto_material_conjunto_zu.style.display="flex"
    objeto_material_conjunto_zv.style.display="flex"
}
